### ISSUE TITLE
Why not parse body as well?

### ISSUE THREAD

**Issue by nicholaswmin** [mariusc23/express-query-boolean#2]
Why not allow parsing `req.body` values as well?

**Comment by motss** [comment]
@nicholaswmin This can be achieved in `bodyParser` with its own `.json()` method.

```js
...
.use(bodyParser.json())
.use(bodyParser.urlencoded({ extended: false })
...
```

**Comment by mariusc23** [comment]
Closing. Also see discussion on #6.
